### ISSUE TITLE
Document Static Statuspage Editing Workflow

### ISSUE THREAD

**Issue by JJediny** [18F/static-statuspage-example#10]
As a system owner I want to know how to add/update incidents using both:
- standard git workflow
- netlify-cms /admin method: https://www.netlifycms.org/docs/open-authoring/

Acceptance Criteria:
- [ ] Example docs for (optional) protected branch Draft -> Review -> Publish workflow.
- [ ] Example docs for standard workflow for one team where all members can publish directly to master.

**Comment by its-a-lisa-at-work** [comment]
Closing based on the decision made on 4/21/20 to close anything that wasn't a Major current Initiative or Notable mention from the [Tech Portfolio Sprint Planning 2020-04-20](https://docs.google.com/document/d/1Q4XRL47tCva3PrIBa5WVcPAtYwv8nFgnyNH6RelnsFc/edit) radiated intent in [slack](https://gsa-tts.slack.com/archives/CNW3GL70S/p1587578121241100) and open for discussion on reopening.
